//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videotapes
    {
        public int ID { get; set; }
        public string NameTapes { get; set; }
        public int Quantity { get; set; }
        public int QuantityAviable { get; set; }
        public Nullable<int> GenreID { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
